#!/usr/bin/python3
def raise_exception_msg(message=""):
    mensaje = "Este es un mensaje de error personalizado"
    
     
    raise NameError(mensaje)
